/**
 * @fileoverview gRPC-Web generated client stub for Auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.1
// source: auth/auth.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as auth_auth_pb from '../auth/auth_pb'; // proto import: "auth/auth.proto"


export class AuthClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSignin = new grpcWeb.MethodDescriptor(
    '/Auth.Auth/Signin',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.SigninRequest,
    auth_auth_pb.SigninResponse,
    (request: auth_auth_pb.SigninRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.SigninResponse.deserializeBinary
  );

  signin(
    request: auth_auth_pb.SigninRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.SigninResponse>;

  signin(
    request: auth_auth_pb.SigninRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.SigninResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.SigninResponse>;

  signin(
    request: auth_auth_pb.SigninRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.SigninResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Auth.Auth/Signin',
        request,
        metadata || {},
        this.methodDescriptorSignin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Auth.Auth/Signin',
    request,
    metadata || {},
    this.methodDescriptorSignin);
  }

}

